apiVersion: v2
name: knit-db-postgres
description: knitfab database (postgres)
type: application
keywords:
  - knitfab
  - MLOps
  - Lineage Tracking
  - Workflow
  - Tag Based Workflow

version: v1.0.0
appVersion: v1.0.0-61101e8
